# podman build -t bead-dev - < dev/Containerfile
FROM python:3.12-slim-trixie

RUN apt update
RUN apt install -y direnv fd-find fzf git less ripgrep tree graphviz unzip sqlite3 visidata pipx npm

# uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# aider
RUN uv venv --python python3.12 /opt/aider
RUN bash -c 'source /opt/aider/bin/activate && uv pip install aider-chat'
ENV PATH="$PATH:/opt/aider/bin"

# opencode
ADD https://github.com/sst/opencode/releases/latest/download/opencode-linux-arm64.zip /tmp/opencode-linux-arm64.zip
RUN unzip /tmp/opencode-linux-arm64.zip -d /opt/opencode && chmod -R a-w /opt/opencode
ENV PATH="$PATH:/opt/opencode"
# RUN mkdir -p /opt/opencode-ai && npm install -g --prefix /opt/opencode-ai opencode-ai
# ENV PATH="$PATH:/opt/opencode-ai/bin"

# gemini-cli
RUN mkdir -p /opt/gemini && npm install -g --prefix /opt/gemini @google/gemini-cli
ENV PATH="$PATH:/opt/gemini/bin"

RUN cat > /opt/bashrc <<EOS
eval "\$(direnv hook bash)"
EOS

ENTRYPOINT ["/bin/bash", "--rcfile", "/opt/bashrc"]
CMD []
