# podman build -t bead-dev - < dev/Containerfile
FROM python:3.12-slim-trixie

RUN apt update
RUN apt install -y direnv fd-find fzf git less ripgrep tree visidata pipx npm htop procps nano
RUN apt install -y graphviz unzip sqlite3 bash zsh fish

# uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV EDITOR=nano

RUN cat > /opt/bashrc <<EOS
eval "\$(direnv hook bash)"
alias l=ls
alias ll='ls -l'
alias gs='git status'
alias gl='git lg'
alias install-claude='npm install -g @anthropic-ai/claude-code'
alias install-gemini='npm install -g @google/gemini-cli'
alias install-opencode='npm install -g opencode-ai'
EOS

ENTRYPOINT ["/bin/bash", "--rcfile", "/opt/bashrc"]
CMD []
