#!/bin/bash
set -x

cd $(dirname "$0")

packages_to_test=(bead bead_cli tests)

pwd
ruff check .
mypy --ignore-missing-imports "${packages_to_test[@]}"

# coverage
if [ "${c}" == "" ]
then
  cov=()
else
  cov=(
      --cov-report=term-missing:skip-covered
      --cov-report=html:coverage
  )
  for dir in ${packages_to_test[@]}
  do
      cov[${#cov[@]}]=--cov=$dir
  done
fi

if [ $# = 0 ]; then
  exec pytest "${cov[@]}" "${packages_to_test[@]}"
else
  exec pytest "${cov[@]}" "$@"
fi
