#!/bin/bash

directories_to_map=(
)

files_to_map=(
    ~/.gitconfig
)

args=(
    --user $(id -u):$(id -g)
    --env "HOME=$HOME"
    --workdir "$PWD"
    --env-file ~/.env
#    --tmpfs ~
    -v $HOME/podman:$HOME
    -v $PWD:$PWD
)

for f in "${files_to_map[@]}"
do
    [ -f "$f" ] || {
        mkdir -p "$(dirname "$f")"
        touch "$f"
    }
    args+=(-v "$f:$f")
done

for d in "${directories_to_map[@]}"
do
    mkdir -p "$d"
    args+=(-v "$d:$d")
done

set -x

exec podman run --rm -it "${args[@]}" bead-dev
